name: Push JSON to Lokalise

on:
  push:
    paths:
      - '**/*.json'  # Trigger on any changes to JSON files
  workflow_dispatch:  # Manual trigger

jobs:
  push-to-lokalise:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Lokalise CLI
        run: |
          # Dynamically fetch the latest release tag
          LOKALISE_CLI_VERSION=$(curl --silent "https://api.github.com/repos/lokalise/lokalise-cli-2-go/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "Downloading Lokalise CLI version: $LOKALISE_CLI_VERSION"

          # Download the appropriate tarball for Linux
          curl -L -o lokalise.tar.gz "https://github.com/lokalise/lokalise-cli-2-go/releases/download/$LOKALISE_CLI_VERSION/lokalise_${LOKALISE_CLI_VERSION}_linux_amd64.tar.gz"

          # Extract and install
          tar -xzf lokalise.tar.gz
          sudo mv lokalise /usr/local/bin/lokalise

      - name: Verify Lokalise CLI Installation
        run: |
          lokalise --version

      - name: Push JSON file to Lokalise
        run: |
          lokalise push \
            --token 919873230a09f13d63d67ab49874325072977cf9 \  # Replace with your Lokalise API token
            --project-id 8924818166f90cfed9af35.66887635 \  # Replace with your Lokalise project ID
            --file-path giacven/test-fun/en.json \  # Specify the path to your JSON file
            --overwrite \
            --lang-en  # Specify the language codes as needed
