name: Push JSON to Lokalise

on:
  push:
    paths:
      - '**/*.json'  # Trigger on any changes to JSON files
  workflow_dispatch:  # Manual trigger

jobs:
  push-to-lokalise:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Lokalise CLI
        run: |
          curl -O https://github.com/lokalise/lokalise-cli-2-go/releases/download/v2.6.0/lokalise_2.6.0_linux_amd64.tar.gz
          tar -xzf lokalise_2.6.0_linux_amd64.tar.gz
          sudo mv lokalise /usr/local/bin/lokalise

      - name: Verify Lokalise CLI Installation
        run: |
          lokalise --version

      - name: Push JSON file to Lokalise
        run: |
          lokalise push \
            --token 919873230a09f13d63d67ab49874325072977cf9 \  # Replace with your Lokalise API token
            --project-id 8924818166f90cfed9af35.66887635 \  # Replace with your Lokalise project ID
            --file-path giacven/test-fun/en.json \  # Specify the path to your JSON file
            --overwrite \
            --lang-en  # Specify the language codes as needed

