- name: Push JSON file to Lokalise
  run: |
    # Check if en.json exists
    if [ ! -f "en.json" ]; then
      echo "Error: en.json file does not exist."
      exit 1
    fi

    # Encode the JSON file in Base64
    BASE64_CONTENT=$(base64 -w 0 en.json)  # Use -w 0 for no line wrapping
    echo "Base64 Content: $BASE64_CONTENT"  # Debugging line

    # Construct the JSON payload
    JSON_PAYLOAD=$(jq -n \
      --arg name "en.json" \
      --arg data "$BASE64_CONTENT" \
      --arg lang_iso "en" \
      --argjson replace_modified true \
      --argjson tags '["auto-updated"]' \
      '{
        files: [
          {
            name: $name,
            data: $data,
            lang_iso: $lang_iso,
            replace_modified: $replace_modified,
            tags: $tags
          }
        ],
        convert_placeholders: false
      }')

    echo "JSON Payload: $JSON_PAYLOAD"  # Debugging line

    # Make the API call
    curl --request POST \
      --url "https://api.lokalise.com/api2/projects/8924818166f90cfed9af35.66887635/files/upload" \
      --header 'accept: application/json' \
      --header 'content-type: application/json' \
      --header "X-Api-Token: 919873230a09f13d63d67ab49874325072977cf9" \
      --data "$JSON_PAYLOAD"
