name: Push JSON to Lokalise

on:
  workflow_dispatch:
  push:
    paths:
      - "en.json"  # Trigger when this file is updated
    branches:
      - main  # Only trigger on changes to the main branch

jobs:
  push-to-lokalise:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate API Token and Project ID
        run: |
          if [ -z "${{ secrets.API_TOKEN }}" ]; then
            echo "Error: API Token is not set."
            exit 1
          fi
          if [ -z "${{ secrets.PROJECT_ID }}" ]; then
            echo "Error: Project ID is not set."
            exit 1
          fi

      - name: Push JSON file to Lokalise
        run: |
          # Check if the file exists
          if [ ! -f "en.json" ]; then
            echo "Error: en.json file not found!"
            exit 1
          fi

          # Send the POST request to upload the file
          response=$(curl -s -o response.json -w "%{http_code}" -X POST "https://api.lokalise.com/api2/projects/${{ secrets.PROJECT_ID }}/files/upload" \
            -H "X-Api-Token: ${{ secrets.API_TOKEN }}" \
            -F "file=@en.json" \
            -F 'data={"convert_placeholders": false, "replace_modified": true, "tags": ["auto-updated"]}')
          
          # Check the response code
          if [[ "$response" -ne 200 ]]; then
            echo "Error: Failed to upload en.json to Lokalise! Response code: $response"
            cat response.json  # Output the response for debugging
            exit 1
          fi
          echo "Successfully uploaded en.json to Lokalise!"
