name: Push JSON to Lokalise

on:
  push:
    paths:
      - 'en.json'  # Modify this path to your JSON file
  workflow_dispatch:  # Enables manual trigger of the workflow

jobs:
  push-to-lokalise:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies (if needed)
      run: |
        sudo apt-get install -y curl jq

    - name: Encode JSON file to Base64 and Push to Lokalise
      run: |
        # Specify your .json file path
        JSON_FILE_PATH='en.json' # Modify this to match your JSON file path

        # Use your Lokalise API Token and Project ID here
        LOKALISE_API_TOKEN='919873230a09f13d63d67ab49874325072977cf9' # Replace with your actual Lokalise API Token
        LOKALISE_PROJECT_ID='8924818166f90cfed9af35.66887635' # Replace with your actual Lokalise Project ID

        # Base64 encode the content of the JSON file
        BASE64_DATA=$(base64 -w 0 $JSON_FILE_PATH)

        # Create JSON payload with replace option included
        JSON_PAYLOAD=$(jq -n \
          --arg data "$BASE64_DATA" \
          --arg filename "en.json" \
          --arg lang_iso "en" \
          '{data: $data, filename: $filename, lang_iso: $lang_iso}')

        # Use Lokalise API to upload the file and overwrite modified keys
        curl -X POST \
          -H "X-Api-Token: $LOKALISE_API_TOKEN" \
          -H "accept: application/json" \
          -H "content-type: application/json" \
          --data '{
            "data": "'"$BASE64_DATA"'",
            "filename": "en.json",
            "lang_iso": "en",
            "replace": true
          }' \
          https://api.lokalise.com/api2/projects/$LOKALISE_PROJECT_ID/files/upload

        echo "File uploaded successfully to Lokalise!"
