name: Push JSON to Lokalise

on:
  push:
    paths:
      - 'path/to/your/file.json'  # Modify this path to your JSON file
  workflow_dispatch:  # Enables manual trigger of the workflow

jobs:
  push-to-lokalise:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies (if needed)
      run: |
        sudo apt-get install -y curl jq

    - name: Push JSON to Lokalise
      run: |
        # Specify your .json file path
        JSON_FILE_PATH='giacven/test-fun/en.json' # Modify this to match your JSON file path

        # Use your Lokalise API Token and Project ID here
        LOKALISE_API_TOKEN='919873230a09f13d63d67ab49874325072977cf9' # Replace with your actual Lokalise API Token
        LOKALISE_PROJECT_ID='8924818166f90cfed9af35.66887635' # Replace with your actual Lokalise Project ID

        # Use Lokalise API to upload the file and overwrite existing data
        curl -X POST \
          -H "Content-Type: multipart/form-data" \
          -H "X-Api-Token: $LOKALISE_API_TOKEN" \
          -F "file=@$JSON_FILE_PATH" \
          -F "data={\"project_id\": \"$LOKALISE_PROJECT_ID\", \"replace\": true, \"langs\": [\"en\"]};type=application/json" \
          https://api.lokalise.com/api2/projects/$LOKALISE_PROJECT_ID/files/upload

        echo "File uploaded successfully to Lokalise!"
